#!/bin/bash

ifdump=$(ubus call network.interface dump)
serverdev=$(echo "$ifdump" | jsonfilter -e "@.interface[@.interface='$(cat /lib/gluon/respondd/client.dev 2>/dev/null)' && @.up=true].device")
uci set ddhcpd.settings.server_interface=$serverdev


