#!/usr/bin/lua

local site = require 'gluon.site'

local uci = require('simple-uci').cursor()

uci:section('firewall', 'rule', 'local_node_dhcp', {
	src = 'local_client',
	name = 'allow_dhcp_local_client',
	dest_port = '67',
	proto = 'udp',
	target = 'ACCEPT'
})

uci:save('dhcp')
uci:save('firewall')
